version: "3"
services:
  frontend:
    build:
      context: ./CRUD-App
      dockerfile: Dockerfile # Make sure this is your Node + npm start Dockerfile
    ports:
      - "3001:3000" # Expose React's 3000 on host port 3001
    depends_on:
      - backend

  backend:
    build:
      context: ./rest-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
